services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  adminer:
    container_name: adminer
    image: adminer:5-standalone
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8080:8080
