services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5      

  db-seeder-postgres:
   container_name: db-seeder-postgres
   build:
    context: .
   ports:
      - "3000:3000"
   environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=myDb
   depends_on:
      postgres:
        condition: service_healthy
   
  adminer:
    container_name: adminer
    image: adminer:5-standalone
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8080:8080
